/**
 * The block the design draws and the backend cannot fill.
 *
 * This is the only primitive that is not in the design, and it is the whole of
 * the placeholder policy (build spec §7) expressed as one component. The design
 * draws an AcoustID confidence percentage, an auto-accept threshold, a disk
 * capacity meter, symlinked collaborations, a Vorbis tag map, a per-album byte
 * size, a scan progress bar. None of those exists in `app/schemas.py`, and each
 * of the three obvious responses is worse than this one:
 *
 *   - **inventing a number** puts a figure on the screen that is simply false,
 *     and a false 87% is indistinguishable from a true one;
 *   - **rendering `0`** is the same lie with a smaller font — `0` is a
 *     measurement, and "nothing has measured this" is not;
 *   - **deleting the block** loses the design's composition and, worse, loses
 *     the record that something is missing. Nobody wires up a gap they cannot
 *     see.
 *
 * So the layout is built exactly as drawn and the datum is replaced by
 * something that could not possibly be mistaken for data: a dashed outline —
 * the only one in the application — over the inset tone, with a mono line
 * naming what the backend would have to provide.
 *
 * `data-placeholder="<needs>"` is not decoration either. It is how a screen
 * test counts the gaps it expects, and how `web/WIRING.md` is generated by
 * grepping rather than by remembering:
 *
 *     grep -ro 'data-placeholder="[^"]*"' web/src | sort -u
 *
 * The `needs` string is therefore written for that table: name the missing
 * FIELD or ENDPOINT, not the feeling ("per-album byte size", not "sizes").
 */

import type { CSSProperties } from 'react'

import { cx } from '@/design/cx'
import type { StyleableProps } from '@/design/types'
import { EM_DASH } from '@/format'

import styles from '@/design/Placeholder/Placeholder.module.css'

/**
 * `block` reserves a panel, `inline` a slot inside a row, `figure` a number.
 * There is no `text` variant: a caption that asserts something false is
 * REWRITTEN to be true (spec §7.3), never placeholdered.
 */
export type PlaceholderVariant = 'block' | 'inline' | 'figure'

export interface PlaceholderProps extends StyleableProps {
  /** What the backend would have to provide. Reads as `not wired — {needs}`. */
  needs: string
  variant?: PlaceholderVariant
  /** Size it to roughly what it replaces, so the composition still reads. */
  minHeight?: number | string
}

const VARIANT: Record<PlaceholderVariant, string | undefined> = {
  block: styles.block,
  inline: styles.inline,
  figure: styles.figure,
}

export function Placeholder({
  needs,
  variant = 'block',
  minHeight,
  className,
}: PlaceholderProps) {
  const style =
    minHeight === undefined
      ? undefined
      : ({
          '--placeholder-min-h':
            typeof minHeight === 'number' ? `${minHeight}px` : minHeight,
        } as CSSProperties)

  return (
    <div
      className={cx(styles.root, VARIANT[variant], className)}
      data-placeholder={needs}
      style={style}
    >
      {variant === 'figure' ? (
        // The em dash from @/format, never a typed character and never a
        // number: `null` means nothing has counted this.
        <span className={styles.dash}>{EM_DASH}</span>
      ) : null}
      <span className={styles.label}>not wired — {needs}</span>
    </div>
  )
}
