using System.Collections.Concurrent;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;

namespace Fonoteca.Fixtures;

/// <summary>
/// Real audio files, generated by ffmpeg rather than committed as binaries.
/// </summary>
/// <remarks>
/// Tag writing cannot be tested honestly against mocks. The failure modes that
/// matter — ID3v2.3-vs-v2.4 frame handling, multi-value Vorbis comments, MP4
/// atom rewriting, embedded artwork survival — only appear when real bytes go
/// through a real encoder. So does everything about <c>fpcalc</c>: a stubbed
/// subprocess proves nothing about a tool that opens files itself.
///
/// Generated, not committed, for two reasons. Binary fixtures in git are opaque
/// in review and grow the clone forever; and a generated corpus can be described
/// — the recipe below says exactly what "a FLAC with artwork" contains, which a
/// checked-in file never does.
///
/// The audio is deliberately not a plain sine tone. Chromaprint works on the
/// spectral shape over time, and a constant tone gives it almost nothing to
/// describe; a chirp mixed with two tones and pink noise produces a fingerprint
/// with real structure, which is what makes a determinism test meaningful.
///
/// Built once per process into a temp directory, deleted by the OS rather than
/// by us — a corpus that survives a crashed run is a debugging aid.
/// </remarks>
public static class Corpus
{
    /// <summary>Seconds of audio. Long enough to fingerprint, short enough to build 12 of them.</summary>
    public const int DurationSeconds = 12;

    /// <summary>The AcoustID baked into <see cref="AlreadyTaggedFlac"/>.</summary>
    public const string PreExistingAcoustId = "1b8a1e2f-0000-4000-8000-000000000001";

    private static readonly Lazy<CorpusFiles> Built = new(Build, LazyThreadSafetyMode.ExecutionAndPublication);

    private static readonly ConcurrentDictionary<string, string> ToolPaths = new(StringComparer.Ordinal);

    /// <summary>
    /// Whether ffmpeg is on PATH. Tests <c>Assert.Skip</c> on this rather than
    /// failing, so a machine without the toolchain degrades instead of lying.
    /// </summary>
    public static bool IsAvailable => FindTool("ffmpeg") is not null;

    /// <summary>Where the generated files live. Building them is the first access.</summary>
    public static string Directory => Built.Value.Root;

    /// <summary>Lossless, no tags, no artwork. The ordinary case.</summary>
    public static string Flac => Built.Value.Flac;

    /// <summary>The same audio as <see cref="Flac"/>, lossily encoded. ID3v2.</summary>
    public static string Mp3 => Built.Value.Mp3;

    /// <summary>The same audio again, in an MP4 container. Freeform atoms.</summary>
    public static string M4a => Built.Value.M4a;

    /// <summary>The same audio again, Vorbis in an Ogg container.</summary>
    public static string Ogg => Built.Value.Ogg;

    /// <summary>FLAC carrying an attached picture, so a write can be proved not to drop it.</summary>
    public static string FlacWithArtwork => Built.Value.FlacWithArtwork;

    /// <summary>FLAC already carrying <see cref="PreExistingAcoustId"/> in an ACOUSTID_ID comment.</summary>
    public static string AlreadyTaggedFlac => Built.Value.AlreadyTagged;

    /// <summary>A FLAC cut off mid-stream. Decodes partly, then fails.</summary>
    public static string TruncatedFlac => Built.Value.Truncated;

    /// <summary>Zero bytes, with an audio extension.</summary>
    public static string EmptyFlac => Built.Value.Empty;

    /// <summary>Text, with an audio extension. The walk will offer it; the decoder will not take it.</summary>
    public static string NotAudioFlac => Built.Value.NotAudio;

    /// <summary>
    /// A FLAC whose name carries spaces, an apostrophe, parentheses and brackets.
    /// </summary>
    /// <remarks>
    /// Not a contrived edge case: <c>Down the Road I Go (2000)</c> and
    /// <c>The House Is Rockin'</c> are both in the library this was written for.
    /// A hand-quoted command line breaks on the first album it meets.
    /// </remarks>
    public static string AwkwardlyNamedFlac => Built.Value.AwkwardName;

    /// <summary>A FLAC with a non-ASCII name, for the same reason.</summary>
    public static string NonAsciiNamedFlac => Built.Value.NonAscii;

    /// <summary>
    /// A playable FLAC with an ID3v2.3 tag glued to the front of it.
    /// </summary>
    /// <remarks>
    /// Not a theoretical malformation: forty files in the library this was
    /// written for are shaped exactly like this, and one of them stopped an
    /// identification pass dead at file 370 of 7,317. FLAC has no business
    /// carrying ID3 — the format says a file begins with <c>fLaC</c> — but
    /// several taggers wrote one anyway, and players are forgiving enough that
    /// nobody noticed for years.
    ///
    /// <b>The unsynchronisation is the whole point of the fixture.</b> A
    /// prepended tag alone is harmless, and so is the unsynchronisation flag on
    /// its own; ATL reads both without complaint. What breaks it is the
    /// combination the real files have — the flag set <i>and</i> the bytes
    /// genuinely unsynchronised, so that undoing it shifts every offset after
    /// the picture. Reading ordinary tag fields still works; reading embedded
    /// pictures throws <see cref="NullReferenceException"/> from inside ATL.
    /// Five variants were built and measured before this one, and the other four
    /// pass — which is why the recipe below is spelled out rather than
    /// approximated.
    ///
    /// The audio is intact, so this file fingerprints perfectly well. That is
    /// what makes it dangerous rather than merely broken: it gets identified,
    /// and only then does anything try to read its tags in order to write one
    /// back.
    /// </remarks>
    public static string Id3PrefixedFlac => Built.Value.Id3Prefixed;

    /// <summary>Every generated file, for a test that wants to sweep the lot.</summary>
    public static IReadOnlyList<string> All => Built.Value.All;

    /// <summary>
    /// Copies chosen fixtures into <paramref name="root"/>, returning their
    /// library-relative names.
    /// </summary>
    /// <remarks>
    /// Copies rather than links, because the tests that use this write to the
    /// files. A test that mutated the shared corpus would leave the next one
    /// asserting against different bytes, and the failure would land somewhere
    /// unrelated.
    /// </remarks>
    public static IReadOnlyList<string> CopyInto(string root, params string[] sources)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(root);
        ArgumentNullException.ThrowIfNull(sources);

        System.IO.Directory.CreateDirectory(root);

        var names = new List<string>(sources.Length);

        foreach (var source in sources)
        {
            var name = Path.GetFileName(source);
            File.Copy(source, Path.Combine(root, name), overwrite: true);
            names.Add(name);
        }

        return names;
    }

    private static CorpusFiles Build()
    {
        var ffmpeg = FindTool("ffmpeg")
            ?? throw new InvalidOperationException(
                "ffmpeg is not on PATH. Source ~/.local/opt/env.sh, or check Corpus.IsAvailable "
                + "and skip the test.");

        var root = Path.Combine(Path.GetTempPath(), "fonoteca-corpus-" + Guid.CreateVersion7().ToString("N"));
        System.IO.Directory.CreateDirectory(root);

        var source = Path.Combine(root, "source.wav");
        var cover = Path.Combine(root, "cover.png");

        // A chirp, two tones and pink noise, mixed. Structure over time is what
        // Chromaprint describes, and a flat tone gives it none.
        Run(ffmpeg,
        [
            "-v", "error", "-y",
            "-f", "lavfi", "-i", Lavfi($"sine=frequency=440:duration={DurationSeconds},volume=0.4"),
            "-f", "lavfi", "-i", Lavfi($"sine=frequency=660:duration={DurationSeconds},volume=0.3"),
            "-f", "lavfi", "-i", Lavfi($"anoisesrc=duration={DurationSeconds}:color=pink:amplitude=0.15"),
            "-filter_complex",
            "[0][1][2]amix=inputs=3:duration=first,"
            + "aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo",
            "-t", DurationSeconds.ToString(CultureInfo.InvariantCulture),
            source,
        ]);

        Run(ffmpeg, ["-v", "error", "-y", "-f", "lavfi", "-i", "color=c=teal:s=120x120:d=1", "-frames:v", "1", cover]);

        var flac = Encode(ffmpeg, source, root, "tone.flac", ["-c:a", "flac"]);
        var mp3 = Encode(ffmpeg, source, root, "tone.mp3", ["-c:a", "libmp3lame", "-b:a", "320k"]);
        var m4a = Encode(ffmpeg, source, root, "tone.m4a", ["-c:a", "aac", "-b:a", "256k"]);
        var ogg = Encode(ffmpeg, source, root, "tone.ogg", ["-c:a", "libvorbis", "-q:a", "6"]);

        var awkward = Encode(ffmpeg, source, root, "Down the Road I Go (2000) - The House Is Rockin'.flac", ["-c:a", "flac"]);
        var nonAscii = Encode(ffmpeg, source, root, "Björk — Jóga [Vespertine].flac", ["-c:a", "flac"]);

        var withArtwork = Path.Combine(root, "artwork.flac");
        Run(ffmpeg,
        [
            "-v", "error", "-y", "-i", source, "-i", cover,
            "-map", "0:a", "-map", "1:v", "-c:a", "flac", "-c:v", "copy",
            "-disposition:v", "attached_pic",
            "-metadata", "TITLE=Corpus",
            "-metadata", "ARTIST=Fonoteca",
            withArtwork,
        ]);

        // Vorbis comments spell it ACOUSTID_ID, which is what Picard writes and
        // what the 227 already-tagged files in the target library carry. Only the
        // FLAC fixture is made this way: ffmpeg's ID3 and MP4 spellings are its
        // own, and assuming them would defeat the point of the round-trip tests.
        var alreadyTagged = Path.Combine(root, "already-tagged.flac");
        Run(ffmpeg,
        [
            "-v", "error", "-y", "-i", source, "-c:a", "flac",
            "-metadata", "ACOUSTID_ID=" + PreExistingAcoustId,
            alreadyTagged,
        ]);

        var truncated = Path.Combine(root, "truncated.flac");
        var whole = File.ReadAllBytes(flac);
        File.WriteAllBytes(truncated, whole[..(whole.Length / 4)]);

        var empty = Path.Combine(root, "empty.flac");
        File.WriteAllBytes(empty, []);

        var notAudio = Path.Combine(root, "not-audio.flac");
        File.WriteAllText(notAudio, "This has an audio extension and no audio in it.\n");

        var id3Prefixed = Path.Combine(root, "id3-prefixed.flac");
        File.WriteAllBytes(id3Prefixed, [.. UnsynchronisedId3Tag(), .. File.ReadAllBytes(flac)]);

        return new CorpusFiles(
            root, flac, mp3, m4a, ogg, withArtwork, alreadyTagged,
            truncated, empty, notAudio, awkward, nonAscii, id3Prefixed);
    }

    /// <summary>
    /// An ID3v2.3 tag carrying a title and a picture, unsynchronised.
    /// </summary>
    /// <remarks>
    /// Hand-built rather than produced by a tool, because no tool in this
    /// toolchain will make one: ffmpeg's FLAC muxer ignores <c>-write_id3v2</c>
    /// and writes a bare <c>fLaC</c> header, which is the correct thing for it to
    /// do and useless here. The bytes are simple enough to state exactly.
    ///
    /// Unsynchronisation is an ID3v2 scheme for keeping tag data from looking
    /// like an MPEG frame sync: every <c>0xFF</c> followed by <c>0x00</c> or by a
    /// byte from <c>0xE0</c> up gets a <c>0x00</c> inserted after it, and the
    /// reader takes them back out. It is pointless in a FLAC — there is no MPEG
    /// sync to protect — which is exactly why a tagger doing it here produces a
    /// file nothing has been tested against. The picture payload is deliberately
    /// full of <c>0xFF</c>, like the JPEG cover art in the real files, so that the
    /// scheme actually has work to do.
    /// </remarks>
    private static byte[] UnsynchronisedId3Tag()
    {
        var picture = new byte[60_000];

        for (var i = 0; i < picture.Length; i++)
        {
            picture[i] = (byte)(i % 7 == 0 ? 0xFF : i % 251);
        }

        byte[] title = [0x00, .. "Corpus"u8];
        byte[] art = [0x00, .. "image/jpeg"u8, 0x00, 0x03, 0x00, .. picture];

        var content = Unsynchronise([.. Id3Frame("TIT2", title), .. Id3Frame("APIC", art)]);

        const int Padding = 512;
        var size = content.Length + Padding;

        // The header's length is a "syncsafe" integer: seven bits per byte, so
        // the length itself can never contain a 0xFF either.
        byte[] syncsafe =
        [
            (byte)((size >> 21) & 0x7f),
            (byte)((size >> 14) & 0x7f),
            (byte)((size >> 7) & 0x7f),
            (byte)(size & 0x7f),
        ];

        // "ID3", version 2.3.0, flags 0x80 = unsynchronisation applied.
        return ["ID3"u8[0], "ID3"u8[1], "ID3"u8[2], 0x03, 0x00, 0x80, .. syncsafe, .. content, .. new byte[Padding]];
    }

    private static byte[] Id3Frame(string id, byte[] payload)
    {
        var size = new byte[4];
        System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(size, payload.Length);

        return [.. System.Text.Encoding.ASCII.GetBytes(id), .. size, 0x00, 0x00, .. payload];
    }

    private static byte[] Unsynchronise(byte[] input)
    {
        var output = new List<byte>(input.Length + 64);

        for (var i = 0; i < input.Length; i++)
        {
            output.Add(input[i]);

            if (input[i] == 0xFF && i + 1 < input.Length && (input[i + 1] == 0x00 || input[i + 1] >= 0xE0))
            {
                output.Add(0x00);
            }
        }

        return [.. output];
    }

    /// <summary>
    /// Wraps a lavfi graph so ffmpeg does not read it as a filename.
    /// </summary>
    /// <remarks>
    /// Kept as a seam: the descriptions are already valid as-is, and the method
    /// exists so a future one that needs escaping has one place to gain it.
    /// </remarks>
    private static string Lavfi(string graph) => graph;

    private static string Encode(
        string ffmpeg, string source, string root, string name, string[] codec)
    {
        var target = Path.Combine(root, name);
        Run(ffmpeg, ["-v", "error", "-y", "-i", source, .. codec, target]);
        return target;
    }

    private static void Run(string fileName, string[] arguments)
    {
        var startInfo = new ProcessStartInfo(fileName)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };

        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = Process.Start(startInfo)
            ?? throw new InvalidOperationException($"Could not start {fileName}.");

        // Both pipes before the wait, for the same reason ProcessRunner does it:
        // a tool that fills one of them never exits.
        var stdout = process.StandardOutput.ReadToEndAsync();
        var stderr = process.StandardError.ReadToEndAsync();

        Task.WaitAll(stdout, stderr);
        process.WaitForExit();

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"{Path.GetFileName(fileName)} exited {process.ExitCode}: {stderr.Result.Trim()}");
        }
    }

    /// <summary>Resolves a tool through PATH once, so building 12 files does not search 12 times.</summary>
    private static string? FindTool(string name) =>
        ToolPaths.TryGetValue(name, out var cached)
            ? cached
            : Resolve(name) is { } found ? ToolPaths[name] = found : null;

    private static string? Resolve(string name)
    {
        var path = Environment.GetEnvironmentVariable("PATH");
        if (string.IsNullOrEmpty(path)) return null;

        foreach (var directory in path.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
        {
            var candidate = Path.Combine(directory, name);

            if (!File.Exists(candidate)) continue;

            if (OperatingSystem.IsWindows()) return candidate;

            try
            {
                // Executable, not merely present — a name collision with a data
                // file would otherwise fail much later and much less clearly.
                if ((File.GetUnixFileMode(candidate) & UnixFileMode.UserExecute) != 0)
                {
                    return candidate;
                }
            }
            catch (IOException)
            {
                // Unreadable entry on PATH; keep looking.
            }
        }

        return null;
    }

    private sealed record CorpusFiles(
        string Root,
        string Flac,
        string Mp3,
        string M4a,
        string Ogg,
        string FlacWithArtwork,
        string AlreadyTagged,
        string Truncated,
        string Empty,
        string NotAudio,
        string AwkwardName,
        string NonAscii,
        string Id3Prefixed)
    {
        public IReadOnlyList<string> All =>
        [
            Flac, Mp3, M4a, Ogg, FlacWithArtwork, AlreadyTagged,
            Truncated, Empty, NotAudio, AwkwardName, NonAscii, Id3Prefixed,
        ];
    }
}
