/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime configuration and catalogue counts. */
        get: operations["GetSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/musicbrainz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which MusicBrainz server is in use, and whether it is answering. */
        get: operations["GetMusicBrainzHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether a scan is running, and what the last one found. */
        get: operations["GetLibraryScanStatus"];
        put?: never;
        /**
         * Reconcile the catalogue's file list with the files on disk.
         * @description Walks the library root, adding files that are new, updating those whose size or modification time changed, and removing rows for files that are gone. Reads no file contents and modifies no file.
         */
        post: operations["ScanLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many files still have no AcoustID, and how the last pass went. */
        get: operations["GetLibraryIdentificationStatus"];
        put?: never;
        /**
         * Fingerprint the files with no AcoustID and look them up.
         * @description Returns immediately with a job id; progress arrives on the jobs hub. This pass opens every file that has not been identified, runs fpcalc on it and asks AcoustID, which enforces three requests a second — so a first pass over a large library is a matter of tens of minutes, not seconds. Tags are only written when Fonoteca:AllowFileMutation is enabled; with it off the pass still fingerprints and identifies everything, so enabling it and running again costs no further lookups.
         */
        post: operations["StartLibraryIdentification"];
        /** Ask the running pass to stop after the file it is on. */
        delete: operations["CancelLibraryIdentification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many identified files have no recording yet, and how the last pass went. */
        get: operations["GetLibraryEnrichmentStatus"];
        put?: never;
        /**
         * Ask MusicBrainz what the identified files are, and file them under artists.
         * @description Returns immediately with a job id; progress arrives on the jobs hub. Takes each identified file's stored fingerprint back to AcoustID for the MusicBrainz recording it names, then fetches that recording and its work — so a first pass over a large library is tens of minutes, paced by AcoustID's three requests a second. Opens no file and modifies none, so it runs even with the library volume unmounted.
         */
        post: operations["StartLibraryEnrichment"];
        /** Ask the running pass to stop after the file it is on. */
        delete: operations["CancelLibraryEnrichment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/attribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many files have no album yet, and how the last pass went. */
        get: operations["GetReleaseAttributionStatus"];
        put?: never;
        /**
         * Work out which album each identified file came from.
         * @description Returns immediately with a job id; progress arrives on the jobs hub. Decides files in sets rather than one at a time — a single file cannot name its release, since one recording appears on the album, on compilations and on every regional pressing. The folders are not consulted: a set is discovered by following shared candidate releases, and the answer is checked against the folders afterwards at GET /api/catalogue/attribution. Opens no file and modifies none.
         */
        post: operations["StartReleaseAttribution"];
        /** Ask the running pass to stop after the set it is on. */
        delete: operations["CancelReleaseAttribution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Artists with at least one track in the library.
         * @description Ordered by sort name. `query` filters on the artist's name, case-insensitively, anywhere in the string. An artist appears here if they are on a recording's credit line, are linked to it as a conductor or ensemble, or wrote the work it performs — and only when at least one file in the library holds that recording.
         */
        get: operations["GetArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One artist and every track of theirs in the library. */
        get: operations["GetArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Albums the library holds at least one track of.
         * @description Ordered by title. `query` filters on the release title, case-insensitively, anywhere in the string. `held` against `trackCount` is what an incomplete rip looks like — though a CD+DVD-Video release is legitimately half missing on an audio-only library, which is why the medium formats are returned beside them.
         */
        get: operations["GetReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/releases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One release and its whole track list, held or not.
         * @description The entire track list as MusicBrainz prints it, with each track flagged for whether the library holds it — so a missing track is visible as a gap rather than as an absence.
         */
        get: operations["GetRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How the attributed albums compare with the folders on disk.
         * @description The folders play no part in deciding which release a file came from. This is where they are used instead: as an independent second opinion. A folder split across releases, or a release spanning folders, is a disagreement worth a person's attention — and either side may be the wrong one.
         */
        get: operations["GetAttributionReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArtistDetailResponse: {
            artist: components["schemas"]["ArtistSummary"];
            tracks: components["schemas"]["TrackRow"][];
        };
        ArtistListResponse: {
            /** Format: int32 */
            total: number;
            items: components["schemas"]["ArtistSummary"][];
        };
        ArtistSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            sortName: null | string;
            disambiguation: null | string;
            type: null | string;
            /** Format: int32 */
            trackCount: number;
        };
        AttributionReportResponse: {
            outcomes: components["schemas"]["OutcomeCount"][];
            /** Format: int32 */
            folders: number;
            /** Format: int32 */
            foldersAgreeing: number;
            foldersSplit: components["schemas"]["FolderDisagreement"][];
            releasesSpanningFolders: components["schemas"]["ReleaseDisagreement"][];
            incomplete: components["schemas"]["IncompleteRelease"][];
        };
        AttributionShare: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            /** Format: int32 */
            files: number;
        };
        AttributionStartedResponse: {
            jobId: string;
            /** Format: int32 */
            pending: number;
        };
        AttributionStatusResponse: {
            running: boolean;
            jobId: null | string;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            total: number;
            currentFile: null | string;
            /** Format: int32 */
            pending: number;
            lastCompleted: null | components["schemas"]["AttributionSummary"];
        };
        AttributionSummary: {
            jobId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            examined: number;
            /** Format: int32 */
            attributed: number;
            /** Format: int32 */
            ambiguous: number;
            /** Format: int32 */
            groupOnly: number;
            /** Format: int32 */
            noConfidentFit: number;
            /** Format: int32 */
            noCandidate: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            components: number;
            /** Format: int32 */
            releases: number;
            cancelled: boolean;
        };
        CatalogueCounts: {
            /** Format: int32 */
            files: number;
            /** Format: int32 */
            recordings: number;
            /** Format: int32 */
            releases: number;
            /** Format: int32 */
            artists: number;
        };
        EnrichmentStartedResponse: {
            jobId: string;
            /** Format: int32 */
            pending: number;
        };
        EnrichmentStatusResponse: {
            running: boolean;
            jobId: null | string;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            total: number;
            currentFile: null | string;
            /** Format: int32 */
            pending: number;
            lastCompleted: null | components["schemas"]["EnrichmentSummary"];
        };
        EnrichmentSummary: {
            jobId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            examined: number;
            /** Format: int32 */
            linked: number;
            /** Format: int32 */
            noRecording: number;
            /** Format: int32 */
            recordingNotFound: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            recordings: number;
            /** Format: int32 */
            works: number;
            /** Format: int32 */
            artists: number;
            cancelled: boolean;
        };
        FileRow: {
            path: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        FolderDisagreement: {
            folder: string;
            releases: components["schemas"]["AttributionShare"][];
        };
        IdentificationStartedResponse: {
            jobId: string;
            /** Format: int32 */
            pending: number;
        };
        IdentificationStatusResponse: {
            running: boolean;
            jobId: null | string;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            total: number;
            currentFile: null | string;
            /** Format: int32 */
            pending: number;
            writesTags: boolean;
            lastCompleted: null | components["schemas"]["IdentificationSummary"];
        };
        IdentificationSummary: {
            jobId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            examined: number;
            /** Format: int32 */
            alreadyTagged: number;
            /** Format: int32 */
            fingerprinted: number;
            /** Format: int32 */
            identified: number;
            /** Format: int32 */
            unknown: number;
            /** Format: int32 */
            ambiguous: number;
            /** Format: int32 */
            belowThreshold: number;
            /** Format: int32 */
            unfingerprintable: number;
            /** Format: int32 */
            tagged: number;
            /** Format: int32 */
            writeRefused: number;
            /** Format: int32 */
            tagUnreadable: number;
            /** Format: int32 */
            failed: number;
            cancelled: boolean;
        };
        IncompleteRelease: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            /** Format: int32 */
            held: number;
            /** Format: int32 */
            trackCount: number;
            formats: null | string;
        };
        LibraryScanStatusResponse: {
            running: boolean;
            lastCompleted: null | components["schemas"]["LibraryScanSummary"];
        };
        LibraryScanSummary: {
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            filesSeen: number;
            /** Format: int32 */
            added: number;
            /** Format: int32 */
            updated: number;
            /** Format: int32 */
            unchanged: number;
            /** Format: int32 */
            removed: number;
            /** Format: int32 */
            unreadableDirectories: number;
        };
        MusicBrainzHealthResponse: {
            server: string;
            isOfficialServer: boolean;
            /** Format: int32 */
            minimumRequestIntervalMs: number;
            contactConfigured: boolean;
            status: components["schemas"]["MusicBrainzReachability"];
            /** Format: int32 */
            latencyMs: null | number;
            detail: null | string;
            /** Format: date-time */
            checkedAtUtc: string;
        };
        /** @enum {unknown} */
        MusicBrainzReachability: "NotConfigured" | "Reachable" | "Unreachable" | "Rejected";
        OutcomeCount: {
            outcome: string;
            /** Format: int32 */
            files: number;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        ReleaseDetailResponse: {
            release: components["schemas"]["ReleaseSummary"];
            tracks: components["schemas"]["ReleaseTrackRow"][];
        };
        ReleaseDisagreement: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            folders: components["schemas"]["AttributionShare"][];
        };
        ReleaseListResponse: {
            /** Format: int32 */
            total: number;
            items: components["schemas"]["ReleaseSummary"][];
        };
        ReleaseSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            artist: null | string;
            /** Format: int32 */
            year: null | number;
            country: null | string;
            status: null | string;
            formats: null | string;
            /** Format: int32 */
            discCount: null | number;
            /** Format: int32 */
            trackCount: number;
            /** Format: int32 */
            held: number;
            /** Format: int32 */
            files: number;
            certainty: string;
            /** Format: int32 */
            editionAlternatives: number;
        };
        ReleaseTrackRow: {
            /** Format: int32 */
            discNumber: number;
            /** Format: int32 */
            position: number;
            number: null | string;
            title: string;
            duration: null | string;
            /** Format: uuid */
            recordingId: string;
            held: boolean;
            files: components["schemas"]["FileRow"][];
        };
        SystemInfoResponse: {
            version: string;
            /** Format: date-time */
            serverTimeUtc: string;
            libraryPath: string;
            fileMutationAllowed: boolean;
            counts: components["schemas"]["CatalogueCounts"];
        };
        TrackAlbum: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            /** Format: int32 */
            year: null | number;
        };
        TrackRow: {
            /** Format: uuid */
            recordingId: string;
            title: string;
            workTitle: null | string;
            duration: null | string;
            roles: string[];
            album: null | components["schemas"]["TrackAlbum"];
            folder: string;
            files: components["schemas"]["FileRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    GetMusicBrainzHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicBrainzHealthResponse"];
                };
            };
        };
    };
    GetLibraryScanStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanStatusResponse"];
                };
            };
        };
    };
    ScanLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanSummary"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetLibraryIdentificationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificationStatusResponse"];
                };
            };
        };
    };
    StartLibraryIdentification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificationStartedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CancelLibraryIdentification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetLibraryEnrichmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentStatusResponse"];
                };
            };
        };
    };
    StartLibraryEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentStartedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CancelLibraryEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetReleaseAttributionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionStatusResponse"];
                };
            };
        };
    };
    StartReleaseAttribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionStartedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CancelReleaseAttribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetArtists: {
        parameters: {
            query?: {
                query?: string;
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistListResponse"];
                };
            };
        };
    };
    GetArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetReleases: {
        parameters: {
            query?: {
                query?: string;
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseListResponse"];
                };
            };
        };
    };
    GetRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAttributionReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionReportResponse"];
                };
            };
        };
    };
}
