/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime configuration and catalogue counts. */
        get: operations["GetSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/musicbrainz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which MusicBrainz server is in use, and whether it is answering. */
        get: operations["GetMusicBrainzHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether a scan is running, and what the last one found. */
        get: operations["GetLibraryScanStatus"];
        put?: never;
        /**
         * Reconcile the catalogue's file list with the files on disk.
         * @description Walks the library root, adding files that are new, updating those whose size or modification time changed, and removing rows for files that are gone. Reads no file contents and modifies no file.
         */
        post: operations["ScanLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many files still have no AcoustID, and how the last pass went. */
        get: operations["GetLibraryIdentificationStatus"];
        put?: never;
        /**
         * Fingerprint the files with no AcoustID and look them up.
         * @description Returns immediately with a job id; progress arrives on the jobs hub. This pass opens every file that has not been identified, runs fpcalc on it and asks AcoustID, which enforces three requests a second — so a first pass over a large library is a matter of tens of minutes, not seconds. Tags are only written when Fonoteca:AllowFileMutation is enabled; with it off the pass still fingerprints and identifies everything, so enabling it and running again costs no further lookups.
         */
        post: operations["StartLibraryIdentification"];
        /** Ask the running pass to stop after the file it is on. */
        delete: operations["CancelLibraryIdentification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many identified files have no recording yet, and how the last pass went. */
        get: operations["GetLibraryEnrichmentStatus"];
        put?: never;
        /**
         * Ask MusicBrainz what the identified files are, and file them under artists.
         * @description Returns immediately with a job id; progress arrives on the jobs hub. Takes each identified file's stored fingerprint back to AcoustID for the MusicBrainz recording it names, then fetches that recording and its work — so a first pass over a large library is tens of minutes, paced by AcoustID's three requests a second. Opens no file and modifies none, so it runs even with the library volume unmounted.
         */
        post: operations["StartLibraryEnrichment"];
        /** Ask the running pass to stop after the file it is on. */
        delete: operations["CancelLibraryEnrichment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/attribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many files have no album yet, and how the last pass went. */
        get: operations["GetReleaseAttributionStatus"];
        put?: never;
        /**
         * Work out which album each identified file came from.
         * @description Returns immediately with a job id; progress arrives on the jobs hub. Decides files in sets rather than one at a time — a single file cannot name its release, since one recording appears on the album, on compilations and on every regional pressing. The folders are not consulted: a set is discovered by following shared candidate releases, and the answer is checked against the folders afterwards at GET /api/catalogue/attribution. Opens no file and modifies none.
         */
        post: operations["StartReleaseAttribution"];
        /** Ask the running pass to stop after the set it is on. */
        delete: operations["CancelReleaseAttribution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Artists with at least one track in the library.
         * @description Ordered by sort name. `query` filters on the artist's name, case-insensitively, anywhere in the string. An artist appears here if they are on a recording's credit line, are linked to it as a conductor or ensemble, or wrote the work it performs — and only when at least one file in the library holds that recording.
         */
        get: operations["GetArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One artist and every track of theirs in the library. */
        get: operations["GetArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Albums the library holds at least one track of.
         * @description Ordered by title. `query` filters on the release title, case-insensitively, anywhere in the string. `held` against `trackCount` is what an incomplete rip looks like — though a CD+DVD-Video release is legitimately half missing on an audio-only library, which is why the medium formats are returned beside them.
         */
        get: operations["GetReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/releases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One release and its whole track list, held or not.
         * @description The entire track list as MusicBrainz prints it, with each track flagged for whether the library holds it — so a missing track is visible as a gap rather than as an absence.
         */
        get: operations["GetRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How the attributed albums compare with the folders on disk.
         * @description The folders play no part in deciding which release a file came from. This is where they are used instead: as an independent second opinion. A folder split across releases, or a release spanning folders, is a disagreement worth a person's attention — and either side may be the wrong one.
         */
        get: operations["GetAttributionReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the passes refused to decide, as questions for a person.
         * @description One entry per open question: a file no pass could identify, or a set of files no release explained. Refusals that are nobody's decision are left out — a lookup that did not answer is transient and stays on the worklist, a file the pass has not reached is a queue position, and a file the decoder could not read is a question about the file rather than about the music. No candidate answers come back here, because nothing records them — they are recovered on demand, per question: `matching/recordings/{id}/candidates` re-asks AcoustID from the file's stored fingerprint, and `matching/components/{stamp}/candidates` asks MusicBrainz again for a whole refused set.
         */
        get: operations["GetOpenQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything one file can be told to say about itself.
         * @description What a person needs in front of them while deciding which recording a file holds, and the half the worklist could not carry. Half of it is catalogue — path, size, the length `fpcalc` measured, what each pass concluded — and half of it is read from the bytes on demand: codec, bitrate, sample rate, bit depth, channels, and whatever the file's own tags still claim.
         *
         *     **Separate from the candidate set on purpose.** This costs one header read and no provider request at all, so it answers for every file on the worklist — including the ones whose candidates cannot be recovered, which are most of them. The measured properties are written back to the catalogue as a side effect, since nothing else populates them yet.
         *
         *     Nothing here fails the request. An unmounted volume, a moved file or a decoder that refuses the container all come back as an absent `audio` block and a `note` saying which, because a file nothing could read is itself worth knowing about on this screen.
         */
        get: operations["GetMatchingFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/files/{id}/art": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The cover art embedded in one file, as it is stored.
         * @description The bytes of the file's own front cover, served unchanged — no scaling, no re-encoding. It is the one claim about an album that a person can check against a candidate at a glance, and unlike the folder name it travels inside the file.
         *
         *     **404 is the ordinary answer, not an error.** A file with no picture, a file no tag parser will open and an unmounted volume all come back the same way, because the screen draws the same monogram for all three.
         */
        get: operations["GetMatchingFileArtwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/recordings/{id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The recordings one file could be, re-asked from its stored fingerprint.
         * @description The candidate set identification weighed and did not record. It is recovered rather than read: the fingerprint is in the catalogue, so AcoustID can be asked the same question again for one request and no disk access at all.
         *
         *     **Answered from the catalogue where it can be.** The identification and enrichment passes store AcoustID's whole answer as they go, and the assembled candidate document is stored the first time anybody asks for it; both are believed for a week. So the ordinary case is a single row read, and the expensive case — one AcoustID turn plus a MusicBrainz recording lookup per candidate, measured at 10.3 seconds each cold — is paid once per file rather than once per click. `refresh=true` skips the stored answer and asks again; `asOfUtc` and `fromCache` say which of the two happened.
         */
        get: operations["GetRecordingCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/recordings/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A person's answer to one file's identification question.
         * @description The commit half of `matching/recordings/{id}/candidates`. `answer` is either `recording`, with the MBID chosen, or `none`, which is the person saying the audio is none of the recordings AcoustID named — a stronger claim than the rule was in a position to make, and the only one that closes the question without an identity. Either way the file is marked as decided by a person, which takes it out of the reach of the identification and enrichment worklists: re-asking a library after a rule change must not silently undo an answer somebody gave.
         *
         *     Choosing a recording links it, writes its artists, works and credits into the catalogue exactly as the enrichment pass would, re-asks AcoustID for the cluster that names it, and writes that cluster into the file's tags — subject to `Fonoteca:AllowFileMutation`, whose refusal comes back as `tag: Refused` rather than as an error. The file then joins the attribution worklist by the same rule every enriched file does.
         */
        post: operations["DecideRecordingMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/components/{stamp}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The albums one refused component could be, gathered again on demand.
         * @description The album-shaped half of the worklist, which used to have no answer at all. `stamp` is the component's identity — the `UtcTicks` of the `ReleaseLookupUtc` every file in it shares, which is the number in the worklist item's `release:` id.
         *
         *     **Gathered live, and nothing caches it.** No candidate set is recorded anywhere, so this browses MusicBrainz for each of the component's distinct recordings, ranks the releases those browses name by how much of the set each holds, and fetches the track lists of the best few to score them with the same `ReleaseFit` the pass uses. Expect seconds rather than milliseconds: it is one gated request per recording plus one per release offered. `browsed` and `recordings` say whether every recording was asked about, and `total` says how many releases were seen before the list was cut.
         *
         *     It takes no lease and writes nothing, so a slow gather refuses no pass.
         */
        get: operations["GetComponentCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/components/{stamp}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A person's answer to one component's album question.
         * @description The commit half of `matching/components/{stamp}/candidates`. `answer` is either `release`, with the MBID chosen, or `none` — the person saying these files came from none of the albums MusicBrainz offered, which closes the question where the pass's refusal leaves it open forever.
         *
         *     Choosing a release writes it, its group and its **whole** track list into the catalogue exactly as the pass would, then links each file the release explains to its own track. Files in the component the release does not explain are left alone and stay on the worklist — a set that was refused as one is not necessarily one album, and filing the remainder under an album that does not list them would be the invention this pass exists to avoid.
         *
         *     Nothing on disk is touched: an album is a catalogue fact, so there is no tag write, no `Fonoteca:AllowFileMutation` and no undo journal — only the decision entry. Every file answered is marked as decided by a person, which takes it out of the attribution worklist for good.
         */
        post: operations["DecideComponentMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/releases/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Albums matching what somebody typed.
         * @description A free-text search of MusicBrainz, for the files no candidate set can be recovered for — the ones AcoustID cannot place, whose only remaining evidence is a person who knows what the album is. `q` takes MusicBrainz's own query syntax, so `artist:` and `date:` work; a MusicBrainz release URL or a bare MBID pasted into it is looked up directly instead of searched for, and comes back as the single result it is.
         *
         *     **This is the one call in the application that needs a search index**, which database replication does not cover. Against a self-hosted mirror it fails where every other MusicBrainz call works — reported as a provider error rather than as an empty list, so 'nothing matches' and 'this server cannot search' stay apart. `score` is MusicBrainz's own relevance and is printed, not ranked on: the order is theirs.
         */
        get: operations["SearchReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/releases/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every position on one album, filled or not.
         * @description The track list a person seats files onto, straight from MusicBrainz and not from the catalogue — the release may well not be in the catalogue yet, since filing files under it is what puts it there.
         *
         *     Every slot the release prints is returned, including the ones nobody holds: the empty ones are what a person is choosing *around*, and a list of only the occupied positions cannot show a rip that skipped track 7. `durationMs` is beside the formatted length so a client can measure a proposed pairing without parsing it back.
         *
         *     `folder` is optional and is the one thing here read from the catalogue: given a library folder, every slot already held by a file *in that folder and filed under this same release* comes back naming it in `heldBy`. An album is rarely wholly unmatched — the passes place most of a rip and leave the two files they could not — so without this the screen offers twenty-one empty positions for one leftover file and proposes seating it on track 1.
         */
        get: operations["GetReleaseSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/folders/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every file in one folder, and what each of them is matched to.
         * @description The whole folder, not the open questions in it — which is the one view of a rip nothing else here offers. The worklist lists what the passes refused, so a folder of sixteen files that were matched wrongly, minus the three that were refused, appears on it as a three-file album; the thirteen that are wrong are on no screen at all.
         *
         *     Each row says whether the file is still an open question and, when it is not, the album, disc, position and track it was filed under, and how certain that was. Ordered by path, so the discs of a set come back in the order they sit in.
         *
         *     A catalogue read and nothing more: no provider call, no file opened, nothing written.
         */
        get: operations["GetFolderContents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/files/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * File a set of chosen files onto a set of chosen album slots.
         * @description The commit half of `matching/releases/search`, and the only write in the application whose seating comes from the request rather than from a rule. Each pair names one file and one `(disc, position)` on the release; the pairing is committed as given, because for these files the person is the evidence — none of them holds a recording MBID, so nothing here could check the claim against anything.
         *
         *     Choosing a release writes it, its group and its whole track list into the catalogue exactly as the attribution pass would, then gives each file the recording its slot names, the track, the release and the group. All three outcomes are set to their by-a-person values and all three decided-stamps are written, which is what takes the files off every pass's worklist for good.
         *
         *     A file that is not currently an open question is skipped rather than rewritten — this endpoint answers refusals, it does not overrule decisions. Nothing on disk is touched: no tag write, no `Fonoteca:AllowFileMutation`, no undo journal, one decision entry naming every pair.
         */
        post: operations["FileFilesUnderRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/folders/unreleased": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Say a folder is nobody's release, so it stops being asked about.
         * @description The other answer to the question `matching/files/release` answers. Some folders are somebody's own compilation — tracks pulled off YouTube, a mixtape, a rip of a set never issued as an album or a single — and no search will ever find them, because there is nothing to find. Left alone they sit on the worklist forever and every pass re-asks about them at the rate limit.
         *
         *     `folder` is a library-relative path and matches everything beneath it, so `Artist/Album` covers its `CD1` and `CD2` and `Artist` covers the lot. Only files that are currently open questions are touched: a file the passes placed confidently keeps its identity, its release and its track, because this says 'stop asking', not 'forget what you know'. Each of the three outcomes is set to `Unreleased` only where that pass had in fact refused.
         *
         *     Nothing on disk is touched — no tag write, no `Fonoteca:AllowFileMutation`, no undo journal, one decision entry naming the folder. Undoing it is a hand-written `UPDATE`, the same as re-asking a library after a rule change.
         */
        post: operations["MarkFolderUnreleased"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/folders/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Say the passes got this folder wrong, and ask it again by hand.
         * @description The answer to a *confident* mistake, which is the one kind nothing else here can reach. A refused file is on the worklist; a wrongly-matched one is on no screen at all — a live set whose tracks AcoustID matched to the studio recordings of the same songs reads as a finished album until somebody plays it.
         *
         *     Every file under `folder` that a pass placed gives up its recording, track, release and release group, and comes back as one folder-shaped question with the outcome `ReopenedByPerson`. Files already waiting on an answer are left exactly as they are: `Unknown` says something true about the audio that `ReopenedByPerson` does not.
         *
         *     **No pass will answer it again.** The three lookup stamps are deliberately left set, because they record that the providers were asked — which is still true, and is what keeps every pass off the file. Clearing them would hand the folder back to the rule that got it wrong, with the same evidence and therefore the same answer. The fingerprint, the AcoustID and any tag already written to disk are all kept; nothing on disk is touched.
         */
        post: operations["ReopenFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/releases/{id}/fingerprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send this album's unknown fingerprints to AcoustID.
         * @description For files whose recording a person chose by hand, which is the only kind worth sending: a pass took its answer from AcoustID in the first place. Submits each stored fingerprint bound to that recording, so the link becomes everyone's. Never automatic — nothing in Fonoteca submits anything unless somebody presses this. Nothing on disk is touched and no tag is written.
         */
        post: operations["ContributeFingerprints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/matching/folders/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A prefilled MusicBrainz “add release” form for one folder.
         * @description For the case every other screen here cannot help with: the album is not in MusicBrainz at all, so there is nothing to search for and nothing to seat files onto. Live sets, private recordings and anything else nobody has entered land here.
         *
         *     Returns the field names and values for MusicBrainz's own release editor, read from the folder's files — title, artist, date and track list, with lengths measured rather than declared. A client POSTs them to `https://musicbrainz.org/release/add`, which opens the editor prefilled in the person's own browser, under their own account. **Fonoteca sends nothing to MusicBrainz**; their write API cannot create a release, and the judgement in an edit is not ours to make. Add `redirect_uri` to the form and MusicBrainz will send the browser back with `release_mbid` on the query string once the edit is saved.
         *
         *     Subfolders become mediums, so a `CD1`/`CD2` rip seeds as two discs. `status` is seeded as `bootleg`, which is what an unissued concert recording is; it is one dropdown to change in the editor and it is worth checking. Reads the files and nothing else — no provider call, no write, nothing touched on disk.
         */
        get: operations["SeedRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcoustIdClusterRow: {
            /** Format: uuid */
            acoustId: string;
            /** Format: double */
            score: number;
            /** Format: int32 */
            recordings: number;
        };
        AlbumFilingPair: {
            /** Format: uuid */
            file: string;
            /** Format: int32 */
            disc: number;
            /** Format: int32 */
            position: number;
        };
        AlbumFilingRequest: {
            /** Format: uuid */
            release: string;
            pairs: components["schemas"]["AlbumFilingPair"][];
        };
        AlbumFilingResponse: {
            /** Format: uuid */
            release: string;
            title: string;
            /** Format: int32 */
            filed: number;
            /** Format: int32 */
            skipped: number;
            detail: string;
        };
        ArtistDetailResponse: {
            artist: components["schemas"]["ArtistSummary"];
            tracks: components["schemas"]["TrackRow"][];
        };
        ArtistListResponse: {
            /** Format: int32 */
            total: number;
            items: components["schemas"]["ArtistSummary"][];
        };
        ArtistSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            sortName: null | string;
            disambiguation: null | string;
            type: null | string;
            /** Format: int32 */
            trackCount: number;
            /** Format: uuid */
            cover: null | string;
        };
        AttributionReportResponse: {
            outcomes: components["schemas"]["OutcomeCount"][];
            /** Format: int32 */
            folders: number;
            /** Format: int32 */
            foldersAgreeing: number;
            foldersSplit: components["schemas"]["FolderDisagreement"][];
            releasesSpanningFolders: components["schemas"]["ReleaseDisagreement"][];
            incomplete: components["schemas"]["IncompleteRelease"][];
        };
        AttributionShare: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            /** Format: int32 */
            files: number;
        };
        AttributionStartedResponse: {
            jobId: string;
            /** Format: int32 */
            pending: number;
        };
        AttributionStatusResponse: {
            running: boolean;
            jobId: null | string;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            total: number;
            currentFile: null | string;
            /** Format: int32 */
            pending: number;
            lastCompleted: null | components["schemas"]["AttributionSummary"];
        };
        AttributionSummary: {
            jobId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            examined: number;
            /** Format: int32 */
            attributed: number;
            /** Format: int32 */
            ambiguous: number;
            /** Format: int32 */
            groupOnly: number;
            /** Format: int32 */
            noConfidentFit: number;
            /** Format: int32 */
            noCandidate: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            components: number;
            /** Format: int32 */
            releases: number;
            cancelled: boolean;
        };
        AudioQualityRow: {
            codec: string;
            /** Format: int32 */
            bitrateKbps: number;
            /** Format: int32 */
            sampleRateHz: number;
            /** Format: int32 */
            bitDepth: null | number;
            /** Format: int32 */
            channels: number;
            lossless: boolean;
            tier: string;
        };
        CandidateAppearance: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            released: null | string;
            country: null | string;
            status: null | string;
            primaryType: null | string;
            /** Format: int32 */
            discNumber: null | number;
            /** Format: int32 */
            trackPosition: null | number;
            trackNumber: null | string;
            /** Format: int32 */
            trackCount: null | number;
        };
        CandidatePerformer: {
            role: string;
            name: string;
            type: null | string;
        };
        CatalogueCounts: {
            /** Format: int32 */
            files: number;
            /** Format: int32 */
            recordings: number;
            /** Format: int32 */
            releases: number;
            /** Format: int32 */
            artists: number;
        };
        ComponentCandidateRow: {
            mbid: string;
            title: string;
            artist: null | string;
            /** Format: int32 */
            year: null | number;
            country: null | string;
            status: null | string;
            primaryType: null | string;
            secondaryTypes: string[];
            formats: null | string;
            /** Format: int32 */
            trackCount: number;
            /** Format: int32 */
            discCount: number;
            /** Format: int32 */
            filesExplained: number;
            /** Format: double */
            coverage: number;
            /** Format: int32 */
            meanDriftMs: null | number;
            official: boolean;
            slots: components["schemas"]["ComponentSlotRow"][];
        };
        ComponentCandidatesResponse: {
            stamp: string;
            /** Format: date-time */
            asOfUtc: string;
            fromCache: boolean;
            /** Format: int32 */
            files: number;
            /** Format: int32 */
            recordings: number;
            /** Format: int32 */
            browsed: number;
            /** Format: int32 */
            total: number;
            /** Format: double */
            minimumCoverage: number;
            /** Format: int32 */
            maximumDriftMs: number;
            candidates: components["schemas"]["ComponentCandidateRow"][];
            fileList: components["schemas"]["ComponentFileRow"][];
        };
        ComponentDecisionRequest: {
            answer: string;
            /** Format: uuid */
            release: null | string;
        };
        ComponentDecisionResponse: {
            stamp: string;
            outcome: string;
            /** Format: uuid */
            release: null | string;
            title: null | string;
            /** Format: int32 */
            decided: number;
            /** Format: int32 */
            stillOpen: number;
            detail: string;
        };
        ComponentFileRow: {
            /** Format: uuid */
            id: string;
            path: string;
            title: null | string;
            duration: null | string;
        };
        ComponentSlotRow: {
            /** Format: int32 */
            discNumber: number;
            /** Format: int32 */
            position: number;
            number: null | string;
            title: string;
            duration: null | string;
            measured: null | string;
            /** Format: int32 */
            driftMs: null | number;
            path: null | string;
            /** Format: int64 */
            sizeBytes: null | number;
        };
        EnrichmentStartedResponse: {
            jobId: string;
            /** Format: int32 */
            pending: number;
        };
        EnrichmentStatusResponse: {
            running: boolean;
            jobId: null | string;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            total: number;
            currentFile: null | string;
            /** Format: int32 */
            pending: number;
            lastCompleted: null | components["schemas"]["EnrichmentSummary"];
        };
        EnrichmentSummary: {
            jobId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            examined: number;
            /** Format: int32 */
            linked: number;
            /** Format: int32 */
            noRecording: number;
            /** Format: int32 */
            recordingNotFound: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            recordings: number;
            /** Format: int32 */
            works: number;
            /** Format: int32 */
            artists: number;
            cancelled: boolean;
        };
        FileRow: {
            path: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        FileTagRow: {
            name: string;
            value: string;
        };
        FingerprintContributionResponse: {
            /** Format: uuid */
            release: string;
            /** Format: int32 */
            submitted: number;
            /** Format: int32 */
            accepted: number;
            detail: string;
        };
        FolderContentsResponse: {
            folder: string;
            /** Format: int32 */
            files: number;
            /** Format: int32 */
            open: number;
            items: components["schemas"]["FolderFileRow"][];
        };
        FolderDisagreement: {
            folder: string;
            releases: components["schemas"]["AttributionShare"][];
        };
        FolderFileRow: {
            /** Format: uuid */
            mediaFileId: string;
            name: string;
            folder: string;
            length: null | string;
            open: boolean;
            reason: null | string;
            recording: null | string;
            /** Format: uuid */
            releaseId: null | string;
            release: null | string;
            /** Format: int32 */
            year: null | number;
            /** Format: int32 */
            disc: null | number;
            /** Format: int32 */
            position: null | number;
            track: null | string;
            certainty: string;
        };
        FolderReopenRequest: {
            folder: string;
        };
        FolderReopenResponse: {
            folder: string;
            /** Format: int32 */
            reopened: number;
            detail: string;
        };
        FolderUnreleasedRequest: {
            folder: string;
        };
        FolderUnreleasedResponse: {
            folder: string;
            /** Format: int32 */
            closed: number;
            detail: string;
        };
        IdentificationStartedResponse: {
            jobId: string;
            /** Format: int32 */
            pending: number;
        };
        IdentificationStatusResponse: {
            running: boolean;
            jobId: null | string;
            /** Format: int32 */
            processed: number;
            /** Format: int32 */
            total: number;
            currentFile: null | string;
            /** Format: int32 */
            pending: number;
            writesTags: boolean;
            lastCompleted: null | components["schemas"]["IdentificationSummary"];
        };
        IdentificationSummary: {
            jobId: string;
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            examined: number;
            /** Format: int32 */
            alreadyTagged: number;
            /** Format: int32 */
            fingerprinted: number;
            /** Format: int32 */
            identified: number;
            /** Format: int32 */
            unknown: number;
            /** Format: int32 */
            ambiguous: number;
            /** Format: int32 */
            belowThreshold: number;
            /** Format: int32 */
            unfingerprintable: number;
            /** Format: int32 */
            tagged: number;
            /** Format: int32 */
            writeRefused: number;
            /** Format: int32 */
            tagUnreadable: number;
            /** Format: int32 */
            failed: number;
            cancelled: boolean;
        };
        IncompleteRelease: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            /** Format: int32 */
            held: number;
            /** Format: int32 */
            trackCount: number;
            formats: null | string;
        };
        LibraryScanStatusResponse: {
            running: boolean;
            lastCompleted: null | components["schemas"]["LibraryScanSummary"];
        };
        LibraryScanSummary: {
            /** Format: date-time */
            startedAtUtc: string;
            /** Format: date-time */
            completedAtUtc: string;
            /** Format: int64 */
            durationMilliseconds: number;
            /** Format: int32 */
            filesSeen: number;
            /** Format: int32 */
            added: number;
            /** Format: int32 */
            updated: number;
            /** Format: int32 */
            unchanged: number;
            /** Format: int32 */
            removed: number;
            /** Format: int32 */
            unreadableDirectories: number;
        };
        MatchingQueueResponse: {
            /** Format: int32 */
            total: number;
            kinds: components["schemas"]["OpenQuestionCount"][];
            reasons: components["schemas"]["OpenQuestionCount"][];
            items: components["schemas"]["OpenQuestion"][];
        };
        MusicBrainzHealthResponse: {
            server: string;
            isOfficialServer: boolean;
            /** Format: int32 */
            minimumRequestIntervalMs: number;
            contactConfigured: boolean;
            status: components["schemas"]["MusicBrainzReachability"];
            /** Format: int32 */
            latencyMs: null | number;
            detail: null | string;
            /** Format: date-time */
            checkedAtUtc: string;
        };
        /** @enum {unknown} */
        MusicBrainzReachability: "NotConfigured" | "Reachable" | "Unreachable" | "Rejected";
        OpenQuestion: {
            id: string;
            kind: string;
            reason: string;
            subject: string;
            folders: string[];
            /** Format: int32 */
            files: number;
            length: null | string;
            size: null | string;
            format: null | string;
        };
        OpenQuestionCount: {
            name: string;
            /** Format: int32 */
            questions: number;
            /** Format: int32 */
            files: number;
        };
        OutcomeCount: {
            outcome: string;
            /** Format: int32 */
            files: number;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        RecordingCandidateRow: {
            /** Format: uuid */
            mbid: string;
            title: null | string;
            artist: null | string;
            disambiguation: null | string;
            length: null | string;
            /** Format: double */
            score: number;
            /** Format: int32 */
            sources: number;
            /** Format: int32 */
            clusters: number;
            release: null | string;
            drift: null | string;
            firstReleased: null | string;
            work: null | string;
            isrcs: string[];
            performers: components["schemas"]["CandidatePerformer"][];
            /** Format: int32 */
            appearances: number;
            releases: components["schemas"]["CandidateAppearance"][];
        };
        RecordingCandidatesResponse: {
            /** Format: uuid */
            mediaFileId: string;
            measured: string;
            clusters: components["schemas"]["AcoustIdClusterRow"][];
            /** Format: int32 */
            total: number;
            candidates: components["schemas"]["RecordingCandidateRow"][];
            /** Format: date-time */
            asOfUtc: string;
            fromCache: boolean;
        };
        RecordingDecisionRequest: {
            answer: string;
            /** Format: uuid */
            recording: null | string;
        };
        RecordingDecisionResponse: {
            /** Format: uuid */
            mediaFileId: string;
            outcome: string;
            enrichment: string;
            /** Format: uuid */
            recording: null | string;
            title: null | string;
            /** Format: uuid */
            acoustId: null | string;
            tag: string;
            detail: null | string;
        };
        ReleaseDetailResponse: {
            release: components["schemas"]["ReleaseSummary"];
            tracks: components["schemas"]["ReleaseTrackRow"][];
            /** Format: int32 */
            contributable: number;
        };
        ReleaseDisagreement: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            folders: components["schemas"]["AttributionShare"][];
        };
        ReleaseListResponse: {
            /** Format: int32 */
            total: number;
            items: components["schemas"]["ReleaseSummary"][];
        };
        ReleaseSearchResponse: {
            query: string;
            /** Format: int32 */
            total: number;
            items: components["schemas"]["ReleaseSearchRow"][];
        };
        ReleaseSearchRow: {
            /** Format: uuid */
            mbid: string;
            title: string;
            artist: null | string;
            /** Format: int32 */
            year: null | number;
            country: null | string;
            status: null | string;
            primaryType: null | string;
            secondaryTypes: string[];
            formats: null | string;
            /** Format: int32 */
            trackCount: number;
            /** Format: int32 */
            discCount: number;
            /** Format: int32 */
            score: null | number;
        };
        ReleaseSeedResponse: {
            folder: string;
            action: string;
            title: string;
            artist: string;
            /** Format: int32 */
            year: null | number;
            /** Format: int32 */
            trackCount: number;
            /** Format: int32 */
            mediumCount: number;
            /** Format: int32 */
            unmeasuredTracks: number;
            fields: components["schemas"]["SeedField"][];
        };
        ReleaseSlotRow: {
            /** Format: int32 */
            discNumber: number;
            /** Format: int32 */
            position: number;
            number: null | string;
            title: string;
            artist: null | string;
            duration: null | string;
            /** Format: int32 */
            durationMs: null | number;
            /** Format: uuid */
            recording: null | string;
            heldBy: null | string;
        };
        ReleaseSlotsResponse: {
            /** Format: uuid */
            mbid: string;
            title: string;
            artist: null | string;
            /** Format: int32 */
            year: null | number;
            country: null | string;
            status: null | string;
            /** Format: uuid */
            releaseGroup: null | string;
            primaryType: null | string;
            secondaryTypes: string[];
            /** Format: int32 */
            discCount: number;
            slots: components["schemas"]["ReleaseSlotRow"][];
        };
        ReleaseSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            mbid: null | string;
            title: string;
            artist: null | string;
            /** Format: int32 */
            year: null | number;
            country: null | string;
            status: null | string;
            formats: null | string;
            /** Format: int32 */
            discCount: null | number;
            /** Format: int32 */
            trackCount: number;
            /** Format: int32 */
            held: number;
            /** Format: int32 */
            files: number;
            certainty: string;
            /** Format: int32 */
            editionAlternatives: number;
        };
        ReleaseTrackRow: {
            /** Format: int32 */
            discNumber: number;
            /** Format: int32 */
            position: number;
            number: null | string;
            title: string;
            duration: null | string;
            /** Format: uuid */
            recordingId: string;
            held: boolean;
            files: components["schemas"]["FileRow"][];
        };
        SeedField: {
            name: string;
            value: string;
        };
        SubjectFileResponse: {
            /** Format: uuid */
            mediaFileId: string;
            path: string;
            folder: string;
            name: string;
            format: string;
            /** Format: int64 */
            sizeBytes: number;
            size: string;
            measured: null | string;
            duration: null | string;
            audio: null | components["schemas"]["AudioQualityRow"];
            identification: string;
            enrichment: string;
            attribution: string;
            /** Format: uuid */
            acoustId: null | string;
            tagged: boolean;
            fingerprinted: boolean;
            integrity: string;
            /** Format: date-time */
            lastScannedUtc: null | string;
            recording: null | string;
            release: null | string;
            tags: components["schemas"]["FileTagRow"][];
            note: null | string;
        };
        SystemInfoResponse: {
            version: string;
            /** Format: date-time */
            serverTimeUtc: string;
            libraryPath: string;
            fileMutationAllowed: boolean;
            counts: components["schemas"]["CatalogueCounts"];
        };
        TrackAlbum: {
            /** Format: uuid */
            releaseId: string;
            title: string;
            /** Format: int32 */
            year: null | number;
        };
        TrackRow: {
            /** Format: uuid */
            recordingId: string;
            title: string;
            workTitle: null | string;
            duration: null | string;
            roles: string[];
            album: null | components["schemas"]["TrackAlbum"];
            folder: string;
            files: components["schemas"]["FileRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    GetMusicBrainzHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicBrainzHealthResponse"];
                };
            };
        };
    };
    GetLibraryScanStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanStatusResponse"];
                };
            };
        };
    };
    ScanLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanSummary"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetLibraryIdentificationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificationStatusResponse"];
                };
            };
        };
    };
    StartLibraryIdentification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificationStartedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CancelLibraryIdentification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetLibraryEnrichmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentStatusResponse"];
                };
            };
        };
    };
    StartLibraryEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentStartedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CancelLibraryEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetReleaseAttributionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionStatusResponse"];
                };
            };
        };
    };
    StartReleaseAttribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionStartedResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CancelReleaseAttribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetArtists: {
        parameters: {
            query?: {
                query?: string;
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistListResponse"];
                };
            };
        };
    };
    GetArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetReleases: {
        parameters: {
            query?: {
                query?: string;
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseListResponse"];
                };
            };
        };
    };
    GetRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAttributionReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionReportResponse"];
                };
            };
        };
    };
    GetOpenQuestions: {
        parameters: {
            query?: {
                skip?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchingQueueResponse"];
                };
            };
        };
    };
    GetMatchingFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectFileResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMatchingFileArtwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetRecordingCandidates: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingCandidatesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DecideRecordingMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordingDecisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDecisionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetComponentCandidates: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                stamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentCandidatesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DecideComponentMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stamp: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComponentDecisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentDecisionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchReleases: {
        parameters: {
            query?: {
                q?: string;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseSearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetReleaseSlots: {
        parameters: {
            query?: {
                folder?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseSlotsResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetFolderContents: {
        parameters: {
            query?: {
                folder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderContentsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    FileFilesUnderRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumFilingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumFilingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    MarkFolderUnreleased: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderUnreleasedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderUnreleasedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReopenFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderReopenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderReopenResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ContributeFingerprints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FingerprintContributionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SeedRelease: {
        parameters: {
            query?: {
                folder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseSeedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
