/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime configuration and catalogue counts. */
        get: operations["GetSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CatalogueCounts: {
            /** Format: int32 */
            files: number | string;
            /** Format: int32 */
            recordings: number | string;
            /** Format: int32 */
            releases: number | string;
            /** Format: int32 */
            artists: number | string;
        };
        SystemInfoResponse: {
            version: string;
            /** Format: date-time */
            serverTimeUtc: string;
            libraryPath: string;
            fileMutationAllowed: boolean;
            counts: components["schemas"]["CatalogueCounts"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
}
