// <auto-generated />
using System;
using System.Collections.Generic;
using Fonoteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fonoteca.Data.Migrations
{
    [DbContext(typeof(FonotecaDbContext))]
    partial class FonotecaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Disambiguation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SortName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasFilter("\"Mbid\" IS NOT NULL");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SortName");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.ArtistCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreditedAs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("JoinPhrase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ReleaseGroupId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ArtistCredits");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AudioHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("text");

                    b.Property<int>("Integrity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastScannedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastVerifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid?>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quality", "Fonoteca.Domain.Catalogue.MediaFile.Quality#AudioQuality", b1 =>
                        {
                            b1.Property<int?>("BitDepth")
                                .HasColumnType("integer");

                            b1.Property<long>("BitrateBps")
                                .HasColumnType("bigint");

                            b1.Property<int>("Channels")
                                .HasColumnType("integer");

                            b1.Property<string>("Codec")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<TimeSpan?>("Duration")
                                .HasColumnType("interval");

                            b1.Property<bool>("IsLossless")
                                .HasColumnType("boolean");

                            b1.Property<int>("SampleRateHz")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AudioHash")
                        .HasFilter("\"AudioHash\" IS NOT NULL");

                    b.HasIndex("ContentHash")
                        .HasFilter("\"ContentHash\" IS NOT NULL");

                    b.HasIndex("Integrity");

                    b.HasIndex("LastScannedUtc");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("RecordingId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasFilter("\"Mbid\" IS NOT NULL");

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("WorkId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribute")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("WorkId");

                    b.HasIndex("SourceType", "SourceId", "Type");

                    b.HasIndex("TargetType", "TargetId", "Type");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CatalogNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Label")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ReleasedOn")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("TrackCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasFilter("\"Mbid\" IS NOT NULL");

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.ReleaseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("FirstReleaseYear")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasFilter("\"Mbid\" IS NOT NULL");

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("ReleaseGroups");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ReleaseId", "DiscNumber", "Position")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Mbid")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasFilter("\"Mbid\" IS NOT NULL");

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Fonoteca.Domain.Events.DomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasFilter("\"CorrelationId\" IS NOT NULL");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("SubjectType", "SubjectId", "OccurredAtUtc");

                    b.ToTable("DomainEvents");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.ArtistCredit", b =>
                {
                    b.HasOne("Fonoteca.Domain.Catalogue.Artist", "Artist")
                        .WithMany("Credits")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonoteca.Domain.Catalogue.Recording", null)
                        .WithMany("Credits")
                        .HasForeignKey("RecordingId");

                    b.HasOne("Fonoteca.Domain.Catalogue.ReleaseGroup", null)
                        .WithMany("Credits")
                        .HasForeignKey("ReleaseGroupId");

                    b.HasOne("Fonoteca.Domain.Catalogue.Release", null)
                        .WithMany("Credits")
                        .HasForeignKey("ReleaseId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.MediaFile", b =>
                {
                    b.HasOne("Fonoteca.Domain.Catalogue.Recording", "Recording")
                        .WithMany("Files")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Recording", b =>
                {
                    b.HasOne("Fonoteca.Domain.Catalogue.Work", "Work")
                        .WithMany("Recordings")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Relationship", b =>
                {
                    b.HasOne("Fonoteca.Domain.Catalogue.Recording", null)
                        .WithMany("Relationships")
                        .HasForeignKey("RecordingId");

                    b.HasOne("Fonoteca.Domain.Catalogue.Work", null)
                        .WithMany("Relationships")
                        .HasForeignKey("WorkId");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Release", b =>
                {
                    b.HasOne("Fonoteca.Domain.Catalogue.ReleaseGroup", "ReleaseGroup")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Track", b =>
                {
                    b.HasOne("Fonoteca.Domain.Catalogue.Recording", "Recording")
                        .WithMany("Tracks")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonoteca.Domain.Catalogue.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Artist", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Recording", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Files");

                    b.Navigation("Relationships");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Release", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.ReleaseGroup", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Fonoteca.Domain.Catalogue.Work", b =>
                {
                    b.Navigation("Recordings");

                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
